# Generated by Django 2.2.6 on 2019-11-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comentario_servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_servicio', models.TextField()),
                ('id_estado', models.CharField(choices=[('p', 'Pesimo'), ('m', 'Malo'), ('r', 'Regular'), ('b', 'Bueno'), ('e', 'Excelente')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='id_estado',
            field=models.CharField(choices=[('r', 'Reservado'), ('e', 'Entregado'), ('f', 'Finalizado')], default='r', max_length=1),
        ),
    ]
